version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
  app:
    image: node:16.14.0
    volumes:
      - '.:/app/'
    working_dir: /app/
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
    command: yarn dev:server