version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
